/**
 * Currently these dont display correctly
 */

import { WebringLinkStyle } from '@/app/globals';

export default function Webrings() {
  return (
    <div id="webrings">
      <DirEmptiness />
    </div>
  );
}

// Generated by https://www.danialtech.com/tools/html-to-jsx-converter
export function DirEmptiness() {
  return (
    <div  style={{ height: '31px', width: '88px' }}>
      <a
        className={WebringLinkStyle}
        style={{ backgroundColor: 'transparent', color: '#0cf02b', textDecoration: 'none' }}
        href="https://dir.emptiness.io"
        target="_blank"
      >
        <div
          style={{ position: 'relative', backgroundColor: '#0cf02b', color: 'black', fontFamily: '"Verdana"', fontSize: '10px', height: '31px', width: '88px', overflow: 'hidden' }}
        >
          <div
            style={{ backgroundColor: 'black', fontSize: '9px', fontWeight: 'bold', position: 'absolute', color: '#0cf02b', transform: 'scalex(-1)', width: 'auto', height: 'auto', top: '0', left: '0', textAlign: 'right', zIndex: '3' }}
          >
            RID$
            <br />
            SSENITPME{">"}
          </div>
          <div
            style={{ backgroundColor: 'black', color: '#0cf02b', opacity: '0.3', fontSize: '9px', fontWeight: 'bold', position: 'absolute', transform: 'scalex(-1)', width: 'auto', height: 'auto', top: '6px', left: '6px', textAlign: 'right', zIndex: '2' }}
          >
            RID$
            <br />
            SSENITPME{">"}
          </div>
          <span
            style={{ backgroundColor: 'black', fontSize: '12px', fontWeight: 'bold', color: '#0cf02b', position: 'absolute', bottom: '0', right: '0', width: 'auto', height: 'auto' }}
          >×</span>
          <span
            style={{ backgroundColor: 'black', width: '3px', height: '31px', position: 'absolute', top: '0', left: '2px' }}
          ></span>
          <span
            style={{ backgroundColor: 'black', width: '3px', height: '31px', position: 'absolute', top: '0', left: '7px' }}
          ></span>
          <span
            style={{ backgroundColor: 'black', width: '3px', height: '31px', position: 'absolute', top: '0', left: '12px' }}
          ></span>
        </div>
      </a>
    </div>
  );
}